# -*- coding: utf-8 -*-
"""IntroProg - Desenvolvimento 6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WPnvmnupfTHEW4hVVeeo7zrXEohryw_6
"""

#Desenvolva um programa que recebe do usuário nome completo e ano de nascimento que seja entre 1922 e 2021.
#A partir dessas informações, o sistema mostrará o nome do usuário e a idade que completou, ou completará, no ano atual (2023).

#Caso o usuário não digite um número ou apareça um inválido no campo do ano, o sistema informará o erro e continuará perguntando até que um valor correto seja preenchido.

print("Digite aqui seu nome completo: ")
nomecompleto=input()

anocorreto = False

def calculadoraIdade(anoatual,anonasc):
  idade = nomecompleto + ", você tem " + str(anoatual-anonasc) + " anos."
  return idade

while anocorreto == False:
  print("Insira seu ano de nascimento e descobrirei sua idade:")
  try:
    anonasc = int(input())
    if (anonasc > 1921) and (anonasc < 2024):
      anocorreto == True
      frase = calculadoraIdade(2023,anonasc)
      print(frase)
      break
    else:
      print("Ano inválido. Por favor, insira um ano entre 1922 e 2023.")
  except:
      print("Carácter inválido! Tente novamente.")